name: Angular Build Deploy
on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - run: npm run ng build --configuration=production 
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id : ${{ vars.PROJECT_ID }}
        workload_identity_provider: 'projects/740948484269/locations/global/workloadIdentityPools/github-actions-cloud-run/providers/github'
        service_account: 'cloudrun-cicd@grocery-list-plus.iam.gserviceaccount.com'
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        project_id : ${{ vars.PROJECT_ID }}

